CRITICAL - 2021-12-02 11:34:31 --> syntax error, unexpected 'esc' (T_STRING), expecting ']'
#0 C:\xampp\apps\b4t\system\Autoloader\Autoloader.php(241): CodeIgniter\Autoloader\Autoloader->includeFile('C:\\xampp\\apps\\b...')
#1 C:\xampp\apps\b4t\system\Autoloader\Autoloader.php(219): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Models\\back...')
#2 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Models\\back...')
#3 C:\xampp\apps\b4t\app\Controllers\backend\UsersController.php(13): spl_autoload_call('App\\Models\\back...')
#4 C:\xampp\apps\b4t\system\CodeIgniter.php(779): App\Controllers\backend\UsersController->__construct()
#5 C:\xampp\apps\b4t\system\CodeIgniter.php(390): CodeIgniter\CodeIgniter->createController()
#6 C:\xampp\apps\b4t\system\CodeIgniter.php(317): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp\htdocs\apps\b4t\index.php(37): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2021-12-02 11:35:47 --> syntax error, unexpected 'else' (T_ELSE)
#0 C:\xampp\apps\b4t\system\Autoloader\Autoloader.php(241): CodeIgniter\Autoloader\Autoloader->includeFile('C:\\xampp\\apps\\b...')
#1 C:\xampp\apps\b4t\system\Autoloader\Autoloader.php(219): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Models\\back...')
#2 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Models\\back...')
#3 C:\xampp\apps\b4t\app\Controllers\backend\UsersController.php(13): spl_autoload_call('App\\Models\\back...')
#4 C:\xampp\apps\b4t\system\CodeIgniter.php(779): App\Controllers\backend\UsersController->__construct()
#5 C:\xampp\apps\b4t\system\CodeIgniter.php(390): CodeIgniter\CodeIgniter->createController()
#6 C:\xampp\apps\b4t\system\CodeIgniter.php(317): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp\htdocs\apps\b4t\index.php(37): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2021-12-02 11:38:11 --> Call to undefined function App\Models\backend\random_string()
#0 C:\xampp\apps\b4t\app\Controllers\backend\UsersController.php(91): App\Models\backend\UsersModel->add(Array)
#1 C:\xampp\apps\b4t\system\CodeIgniter.php(802): App\Controllers\backend\UsersController->addAction()
#2 C:\xampp\apps\b4t\system\CodeIgniter.php(399): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\backend\UsersController))
#3 C:\xampp\apps\b4t\system\CodeIgniter.php(317): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\apps\b4t\index.php(37): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2021-12-02 11:38:28 --> Call to undefined function App\Models\backend\random_string()
#0 C:\xampp\apps\b4t\app\Controllers\backend\UsersController.php(91): App\Models\backend\UsersModel->add(Array)
#1 C:\xampp\apps\b4t\system\CodeIgniter.php(802): App\Controllers\backend\UsersController->addAction()
#2 C:\xampp\apps\b4t\system\CodeIgniter.php(399): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\backend\UsersController))
#3 C:\xampp\apps\b4t\system\CodeIgniter.php(317): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\apps\b4t\index.php(37): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2021-12-02 11:39:50 --> Undefined property: stdClass::$users_activation_hash
#0 C:\xampp\apps\b4t\app\Models\backend\UsersModel.php(100): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined prope...', 'C:\\xampp\\apps\\b...', 100, Array)
#1 C:\xampp\apps\b4t\app\Controllers\backend\UsersController.php(91): App\Models\backend\UsersModel->add(Array)
#2 C:\xampp\apps\b4t\system\CodeIgniter.php(802): App\Controllers\backend\UsersController->addAction()
#3 C:\xampp\apps\b4t\system\CodeIgniter.php(399): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\backend\UsersController))
#4 C:\xampp\apps\b4t\system\CodeIgniter.php(317): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 C:\xampp\htdocs\apps\b4t\index.php(37): CodeIgniter\CodeIgniter->run()
#6 {main}
ERROR - 2021-12-02 13:12:38 --> Unknown column 'users_activation_hash_expires' in 'field list'
CRITICAL - 2021-12-02 13:12:38 --> Unknown column 'users_activation_hash_expires' in 'field list'
#0 C:\xampp\apps\b4t\system\Database\MySQLi\Connection.php(280): mysqli->query('SELECT `users_i...')
#1 C:\xampp\apps\b4t\system\Database\BaseConnection.php(663): CodeIgniter\Database\MySQLi\Connection->execute('SELECT `users_i...')
#2 C:\xampp\apps\b4t\system\Database\BaseConnection.php(591): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT `users_i...')
#3 C:\xampp\apps\b4t\system\Database\BaseBuilder.php(1428): CodeIgniter\Database\BaseConnection->query('SELECT `users_i...', Array, false)
#4 C:\xampp\apps\b4t\app\Models\backend\BackendModel.php(147): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\apps\b4t\app\Models\backend\UsersModel.php(96): App\Models\backend\BackendModel->getID(1)
#6 C:\xampp\apps\b4t\app\Controllers\backend\UsersController.php(91): App\Models\backend\UsersModel->add(Array)
#7 C:\xampp\apps\b4t\system\CodeIgniter.php(802): App\Controllers\backend\UsersController->addAction()
#8 C:\xampp\apps\b4t\system\CodeIgniter.php(399): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\backend\UsersController))
#9 C:\xampp\apps\b4t\system\CodeIgniter.php(317): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\apps\b4t\index.php(37): CodeIgniter\CodeIgniter->run()
#11 {main}
CRITICAL - 2021-12-02 13:53:13 --> syntax error, unexpected '$email' (T_VARIABLE)
#0 C:\xampp\apps\b4t\system\Autoloader\Autoloader.php(241): CodeIgniter\Autoloader\Autoloader->includeFile('C:\\xampp\\apps\\b...')
#1 C:\xampp\apps\b4t\system\Autoloader\Autoloader.php(219): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Models\\back...')
#2 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Models\\back...')
#3 C:\xampp\apps\b4t\app\Models\backend\UsersModel.php(5): spl_autoload_call('App\\Models\\back...')
#4 C:\xampp\apps\b4t\system\Autoloader\Autoloader.php(264): include_once('C:\\xampp\\apps\\b...')
#5 C:\xampp\apps\b4t\system\Autoloader\Autoloader.php(241): CodeIgniter\Autoloader\Autoloader->includeFile('C:\\xampp\\apps\\b...')
#6 C:\xampp\apps\b4t\system\Autoloader\Autoloader.php(219): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Models\\back...')
#7 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Models\\back...')
#8 C:\xampp\apps\b4t\app\Controllers\backend\UsersController.php(13): spl_autoload_call('App\\Models\\back...')
#9 C:\xampp\apps\b4t\system\CodeIgniter.php(779): App\Controllers\backend\UsersController->__construct()
#10 C:\xampp\apps\b4t\system\CodeIgniter.php(390): CodeIgniter\CodeIgniter->createController()
#11 C:\xampp\apps\b4t\system\CodeIgniter.php(317): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\apps\b4t\index.php(37): CodeIgniter\CodeIgniter->run()
#13 {main}
CRITICAL - 2021-12-02 13:54:43 --> Undefined index: activation
#0 C:\xampp\apps\b4t\app\Models\backend\BackendModel.php(361): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined index...', 'C:\\xampp\\apps\\b...', 361, Array)
#1 C:\xampp\apps\b4t\app\Models\backend\UsersModel.php(107): App\Models\backend\BackendModel->sendEmail(Array)
#2 C:\xampp\apps\b4t\app\Controllers\backend\UsersController.php(91): App\Models\backend\UsersModel->add(Array)
#3 C:\xampp\apps\b4t\system\CodeIgniter.php(802): App\Controllers\backend\UsersController->addAction()
#4 C:\xampp\apps\b4t\system\CodeIgniter.php(399): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\backend\UsersController))
#5 C:\xampp\apps\b4t\system\CodeIgniter.php(317): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\apps\b4t\index.php(37): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2021-12-02 14:00:24 --> Class 'App\Models\backend\AuthModel' not found
#0 C:\xampp\apps\b4t\system\CodeIgniter.php(779): App\Controllers\backend\AuthController->__construct()
#1 C:\xampp\apps\b4t\system\CodeIgniter.php(390): CodeIgniter\CodeIgniter->createController()
#2 C:\xampp\apps\b4t\system\CodeIgniter.php(317): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 C:\xampp\htdocs\apps\b4t\index.php(37): CodeIgniter\CodeIgniter->run()
#4 {main}
CRITICAL - 2021-12-02 14:01:00 --> Undefined variable: title
#0 C:\xampp\apps\b4t\app\Views\frontend\template\header_view.php(40): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined varia...', 'C:\\xampp\\apps\\b...', 40, Array)
#1 C:\xampp\apps\b4t\system\View\View.php(214): include('C:\\xampp\\apps\\b...')
#2 C:\xampp\apps\b4t\system\View\View.php(217): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#3 C:\xampp\apps\b4t\system\Common.php(1092): CodeIgniter\View\View->render('frontend/templa...', Array, true)
#4 C:\xampp\apps\b4t\app\Views\frontend\template\main_view.php(1): view('frontend/templa...')
#5 C:\xampp\apps\b4t\system\View\View.php(214): include('C:\\xampp\\apps\\b...')
#6 C:\xampp\apps\b4t\system\View\View.php(217): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#7 C:\xampp\apps\b4t\system\View\View.php(230): CodeIgniter\View\View->render('frontend/templa...', Array, true)
#8 C:\xampp\apps\b4t\system\Common.php(1092): CodeIgniter\View\View->render('backend/auth/se...', Array, true)
#9 C:\xampp\apps\b4t\app\Controllers\backend\AuthController.php(57): view('backend/auth/se...', Array)
#10 C:\xampp\apps\b4t\system\CodeIgniter.php(802): App\Controllers\backend\AuthController->setPassword('58be9b2f0ea5eed...')
#11 C:\xampp\apps\b4t\system\CodeIgniter.php(399): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\backend\AuthController))
#12 C:\xampp\apps\b4t\system\CodeIgniter.php(317): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#13 C:\xampp\htdocs\apps\b4t\index.php(37): CodeIgniter\CodeIgniter->run()
#14 {main}
CRITICAL - 2021-12-02 15:02:31 --> Cannot access protected property App\Models\backend\AuthModel::$setPasswordRules
#0 C:\xampp\apps\b4t\system\CodeIgniter.php(802): App\Controllers\backend\AuthController->setPasswordAction()
#1 C:\xampp\apps\b4t\system\CodeIgniter.php(399): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\backend\AuthController))
#2 C:\xampp\apps\b4t\system\CodeIgniter.php(317): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 C:\xampp\htdocs\apps\b4t\index.php(37): CodeIgniter\CodeIgniter->run()
#4 {main}
CRITICAL - 2021-12-02 15:02:34 --> Cannot access protected property App\Models\backend\AuthModel::$setPasswordRules
#0 C:\xampp\apps\b4t\system\CodeIgniter.php(802): App\Controllers\backend\AuthController->setPasswordAction()
#1 C:\xampp\apps\b4t\system\CodeIgniter.php(399): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\backend\AuthController))
#2 C:\xampp\apps\b4t\system\CodeIgniter.php(317): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 C:\xampp\htdocs\apps\b4t\index.php(37): CodeIgniter\CodeIgniter->run()
#4 {main}
CRITICAL - 2021-12-02 15:02:35 --> Cannot access protected property App\Models\backend\AuthModel::$setPasswordRules
#0 C:\xampp\apps\b4t\system\CodeIgniter.php(802): App\Controllers\backend\AuthController->setPasswordAction()
#1 C:\xampp\apps\b4t\system\CodeIgniter.php(399): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\backend\AuthController))
#2 C:\xampp\apps\b4t\system\CodeIgniter.php(317): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 C:\xampp\htdocs\apps\b4t\index.php(37): CodeIgniter\CodeIgniter->run()
#4 {main}
CRITICAL - 2021-12-02 15:52:18 --> Call to undefined method CodeIgniter\Database\MySQLi\Result::limit()
#0 C:\xampp\apps\b4t\system\Validation\Validation.php(277): App\Validation\CustomRules->checkActivationCode('58be9b2f0ea5eed...', NULL)
#1 C:\xampp\apps\b4t\system\Validation\Validation.php(151): CodeIgniter\Validation\Validation->processRules('auth_code', 'backend/auth.fo...', '58be9b2f0ea5eed...', Array, Array)
#2 C:\xampp\apps\b4t\system\Controller.php(160): CodeIgniter\Validation\Validation->run()
#3 C:\xampp\apps\b4t\app\Controllers\backend\AuthController.php(68): CodeIgniter\Controller->validate(Array)
#4 C:\xampp\apps\b4t\system\CodeIgniter.php(802): App\Controllers\backend\AuthController->setPasswordAction()
#5 C:\xampp\apps\b4t\system\CodeIgniter.php(399): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\backend\AuthController))
#6 C:\xampp\apps\b4t\system\CodeIgniter.php(317): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp\htdocs\apps\b4t\index.php(37): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2021-12-02 15:53:30 --> Call to undefined method CodeIgniter\Database\MySQLi\Connection::select()
#0 C:\xampp\apps\b4t\app\Controllers\backend\AuthController.php(79): App\Models\backend\AuthModel->setPassword(Array)
#1 C:\xampp\apps\b4t\system\CodeIgniter.php(802): App\Controllers\backend\AuthController->setPasswordAction()
#2 C:\xampp\apps\b4t\system\CodeIgniter.php(399): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\backend\AuthController))
#3 C:\xampp\apps\b4t\system\CodeIgniter.php(317): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\apps\b4t\index.php(37): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2021-12-02 15:54:24 --> Call to undefined method CodeIgniter\Database\MySQLi\Connection::select()
#0 C:\xampp\apps\b4t\app\Controllers\backend\AuthController.php(79): App\Models\backend\AuthModel->setPassword(Array)
#1 C:\xampp\apps\b4t\system\CodeIgniter.php(802): App\Controllers\backend\AuthController->setPasswordAction()
#2 C:\xampp\apps\b4t\system\CodeIgniter.php(399): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\backend\AuthController))
#3 C:\xampp\apps\b4t\system\CodeIgniter.php(317): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\apps\b4t\index.php(37): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2021-12-02 15:55:46 --> Call to a member function limit() on bool
#0 C:\xampp\apps\b4t\app\Controllers\backend\AuthController.php(79): App\Models\backend\AuthModel->setPassword(Array)
#1 C:\xampp\apps\b4t\system\CodeIgniter.php(802): App\Controllers\backend\AuthController->setPasswordAction()
#2 C:\xampp\apps\b4t\system\CodeIgniter.php(399): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\backend\AuthController))
#3 C:\xampp\apps\b4t\system\CodeIgniter.php(317): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\apps\b4t\index.php(37): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2021-12-02 16:22:16 --> syntax error, unexpected ')'
#0 C:\xampp\apps\b4t\system\Autoloader\Autoloader.php(241): CodeIgniter\Autoloader\Autoloader->includeFile('C:\\xampp\\apps\\b...')
#1 C:\xampp\apps\b4t\system\Autoloader\Autoloader.php(219): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Validation\\...')
#2 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Validation\\...')
#3 C:\xampp\apps\b4t\system\Validation\Validation.php(497): spl_autoload_call('App\\Validation\\...')
#4 C:\xampp\apps\b4t\system\Validation\Validation.php(115): CodeIgniter\Validation\Validation->loadRuleSets()
#5 C:\xampp\apps\b4t\system\Controller.php(160): CodeIgniter\Validation\Validation->run()
#6 C:\xampp\apps\b4t\app\Controllers\backend\AuthController.php(32): CodeIgniter\Controller->validate(Array)
#7 C:\xampp\apps\b4t\system\CodeIgniter.php(802): App\Controllers\backend\AuthController->loginAction()
#8 C:\xampp\apps\b4t\system\CodeIgniter.php(399): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\backend\AuthController))
#9 C:\xampp\apps\b4t\system\CodeIgniter.php(317): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\apps\b4t\index.php(37): CodeIgniter\CodeIgniter->run()
#11 {main}
CRITICAL - 2021-12-02 16:22:31 --> syntax error, unexpected ')'
#0 C:\xampp\apps\b4t\system\Autoloader\Autoloader.php(241): CodeIgniter\Autoloader\Autoloader->includeFile('C:\\xampp\\apps\\b...')
#1 C:\xampp\apps\b4t\system\Autoloader\Autoloader.php(219): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Validation\\...')
#2 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Validation\\...')
#3 C:\xampp\apps\b4t\system\Validation\Validation.php(497): spl_autoload_call('App\\Validation\\...')
#4 C:\xampp\apps\b4t\system\Validation\Validation.php(115): CodeIgniter\Validation\Validation->loadRuleSets()
#5 C:\xampp\apps\b4t\system\Controller.php(160): CodeIgniter\Validation\Validation->run()
#6 C:\xampp\apps\b4t\app\Controllers\backend\AuthController.php(32): CodeIgniter\Controller->validate(Array)
#7 C:\xampp\apps\b4t\system\CodeIgniter.php(802): App\Controllers\backend\AuthController->loginAction()
#8 C:\xampp\apps\b4t\system\CodeIgniter.php(399): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\backend\AuthController))
#9 C:\xampp\apps\b4t\system\CodeIgniter.php(317): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\apps\b4t\index.php(37): CodeIgniter\CodeIgniter->run()
#11 {main}
CRITICAL - 2021-12-02 16:44:48 --> Undefined index: users_email
#0 C:\xampp\apps\b4t\app\Models\backend\AuthModel.php(38): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined index...', 'C:\\xampp\\apps\\b...', 38, Array)
#1 C:\xampp\apps\b4t\app\Controllers\backend\AuthController.php(43): App\Models\backend\AuthModel->login(Array)
#2 C:\xampp\apps\b4t\system\CodeIgniter.php(802): App\Controllers\backend\AuthController->loginAction()
#3 C:\xampp\apps\b4t\system\CodeIgniter.php(399): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\backend\AuthController))
#4 C:\xampp\apps\b4t\system\CodeIgniter.php(317): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 C:\xampp\htdocs\apps\b4t\index.php(37): CodeIgniter\CodeIgniter->run()
#6 {main}
CRITICAL - 2021-12-02 16:45:08 --> Undefined index: users_email
#0 C:\xampp\apps\b4t\app\Models\backend\AuthModel.php(38): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined index...', 'C:\\xampp\\apps\\b...', 38, Array)
#1 C:\xampp\apps\b4t\app\Controllers\backend\AuthController.php(43): App\Models\backend\AuthModel->login(Array)
#2 C:\xampp\apps\b4t\system\CodeIgniter.php(802): App\Controllers\backend\AuthController->loginAction()
#3 C:\xampp\apps\b4t\system\CodeIgniter.php(399): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\backend\AuthController))
#4 C:\xampp\apps\b4t\system\CodeIgniter.php(317): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 C:\xampp\htdocs\apps\b4t\index.php(37): CodeIgniter\CodeIgniter->run()
#6 {main}
ERROR - 2021-12-02 16:45:47 --> Unknown column 'users_hash_password' in 'field list'
CRITICAL - 2021-12-02 16:45:47 --> Unknown column 'users_hash_password' in 'field list'
#0 C:\xampp\apps\b4t\system\Database\MySQLi\Connection.php(280): mysqli->query('SELECT `users_s...')
#1 C:\xampp\apps\b4t\system\Database\BaseConnection.php(663): CodeIgniter\Database\MySQLi\Connection->execute('SELECT `users_s...')
#2 C:\xampp\apps\b4t\system\Database\BaseConnection.php(591): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT `users_s...')
#3 C:\xampp\apps\b4t\system\Database\BaseBuilder.php(1561): CodeIgniter\Database\BaseConnection->query('SELECT `users_s...', Array, false)
#4 C:\xampp\apps\b4t\app\Models\backend\AuthModel.php(40): CodeIgniter\Database\BaseBuilder->getWhere(Array)
#5 C:\xampp\apps\b4t\app\Controllers\backend\AuthController.php(43): App\Models\backend\AuthModel->login(Array)
#6 C:\xampp\apps\b4t\system\CodeIgniter.php(802): App\Controllers\backend\AuthController->loginAction()
#7 C:\xampp\apps\b4t\system\CodeIgniter.php(399): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\backend\AuthController))
#8 C:\xampp\apps\b4t\system\CodeIgniter.php(317): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\apps\b4t\index.php(37): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2021-12-02 17:24:49 --> Undefined property: stdClass::$users_name
#0 C:\xampp\apps\b4t\app\Views\backend\users\partials\_show_all_view.php(42): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined prope...', 'C:\\xampp\\apps\\b...', 42, Array)
#1 C:\xampp\apps\b4t\system\View\View.php(214): include('C:\\xampp\\apps\\b...')
#2 C:\xampp\apps\b4t\system\View\View.php(217): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#3 C:\xampp\apps\b4t\system\Common.php(1092): CodeIgniter\View\View->render('backend/users/p...', Array, true)
#4 C:\xampp\apps\b4t\app\Controllers\backend\UsersController.php(42): view('backend/users/p...', Array)
#5 C:\xampp\apps\b4t\system\CodeIgniter.php(802): App\Controllers\backend\UsersController->showAllAction()
#6 C:\xampp\apps\b4t\system\CodeIgniter.php(399): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\backend\UsersController))
#7 C:\xampp\apps\b4t\system\CodeIgniter.php(317): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\apps\b4t\index.php(37): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2021-12-02 17:29:33 --> Undefined property: stdClass::$users_name
#0 C:\xampp\apps\b4t\app\Views\backend\users\partials\_show_all_view.php(42): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined prope...', 'C:\\xampp\\apps\\b...', 42, Array)
#1 C:\xampp\apps\b4t\system\View\View.php(214): include('C:\\xampp\\apps\\b...')
#2 C:\xampp\apps\b4t\system\View\View.php(217): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#3 C:\xampp\apps\b4t\system\Common.php(1092): CodeIgniter\View\View->render('backend/users/p...', Array, true)
#4 C:\xampp\apps\b4t\app\Controllers\backend\UsersController.php(42): view('backend/users/p...', Array)
#5 C:\xampp\apps\b4t\system\CodeIgniter.php(802): App\Controllers\backend\UsersController->showAllAction()
#6 C:\xampp\apps\b4t\system\CodeIgniter.php(399): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\backend\UsersController))
#7 C:\xampp\apps\b4t\system\CodeIgniter.php(317): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\apps\b4t\index.php(37): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2021-12-02 17:30:13 --> Undefined property: stdClass::$users_name
#0 C:\xampp\apps\b4t\app\Views\backend\users\partials\_show_all_view.php(42): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined prope...', 'C:\\xampp\\apps\\b...', 42, Array)
#1 C:\xampp\apps\b4t\system\View\View.php(214): include('C:\\xampp\\apps\\b...')
#2 C:\xampp\apps\b4t\system\View\View.php(217): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#3 C:\xampp\apps\b4t\system\Common.php(1092): CodeIgniter\View\View->render('backend/users/p...', Array, true)
#4 C:\xampp\apps\b4t\app\Controllers\backend\UsersController.php(42): view('backend/users/p...', Array)
#5 C:\xampp\apps\b4t\system\CodeIgniter.php(802): App\Controllers\backend\UsersController->showAllAction()
#6 C:\xampp\apps\b4t\system\CodeIgniter.php(399): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\backend\UsersController))
#7 C:\xampp\apps\b4t\system\CodeIgniter.php(317): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\apps\b4t\index.php(37): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2021-12-02 17:34:40 --> Undefined property: stdClass::$users_status
#0 C:\xampp\apps\b4t\app\Views\backend\users\partials\_show_all_view.php(93): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined prope...', 'C:\\xampp\\apps\\b...', 93, Array)
#1 C:\xampp\apps\b4t\system\View\View.php(214): include('C:\\xampp\\apps\\b...')
#2 C:\xampp\apps\b4t\system\View\View.php(217): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#3 C:\xampp\apps\b4t\system\Common.php(1092): CodeIgniter\View\View->render('backend/users/p...', Array, true)
#4 C:\xampp\apps\b4t\app\Controllers\backend\UsersController.php(42): view('backend/users/p...', Array)
#5 C:\xampp\apps\b4t\system\CodeIgniter.php(802): App\Controllers\backend\UsersController->showAllAction()
#6 C:\xampp\apps\b4t\system\CodeIgniter.php(399): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\backend\UsersController))
#7 C:\xampp\apps\b4t\system\CodeIgniter.php(317): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\apps\b4t\index.php(37): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2021-12-02 17:35:14 --> Undefined property: stdClass::$users_name
#0 C:\xampp\apps\b4t\app\Views\backend\users\partials\_show_all_view.php(105): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined prope...', 'C:\\xampp\\apps\\b...', 105, Array)
#1 C:\xampp\apps\b4t\system\View\View.php(214): include('C:\\xampp\\apps\\b...')
#2 C:\xampp\apps\b4t\system\View\View.php(217): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#3 C:\xampp\apps\b4t\system\Common.php(1092): CodeIgniter\View\View->render('backend/users/p...', Array, true)
#4 C:\xampp\apps\b4t\app\Controllers\backend\UsersController.php(42): view('backend/users/p...', Array)
#5 C:\xampp\apps\b4t\system\CodeIgniter.php(802): App\Controllers\backend\UsersController->showAllAction()
#6 C:\xampp\apps\b4t\system\CodeIgniter.php(399): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\backend\UsersController))
#7 C:\xampp\apps\b4t\system\CodeIgniter.php(317): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\apps\b4t\index.php(37): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2021-12-02 18:13:09 --> Invalid file: backend/users/show_view.php
#0 C:\xampp\apps\b4t\system\View\View.php(198): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('backend/users/s...')
#1 C:\xampp\apps\b4t\system\Common.php(1092): CodeIgniter\View\View->render('backend/users/s...', Array, true)
#2 C:\xampp\apps\b4t\app\Controllers\backend\UsersController.php(136): view('backend/users/s...', Array)
#3 C:\xampp\apps\b4t\system\CodeIgniter.php(802): App\Controllers\backend\UsersController->show(6)
#4 C:\xampp\apps\b4t\system\CodeIgniter.php(399): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\backend\UsersController))
#5 C:\xampp\apps\b4t\system\CodeIgniter.php(317): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\apps\b4t\index.php(37): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2021-12-02 18:13:58 --> Invalid file: backend/users/partials/_show_view.php
#0 C:\xampp\apps\b4t\system\View\View.php(198): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('backend/users/p...')
#1 C:\xampp\apps\b4t\system\View\View.php(432): CodeIgniter\View\View->render('backend/users/p...', NULL, true)
#2 C:\xampp\apps\b4t\app\Views\backend\users\show_view.php(34): CodeIgniter\View\View->include('backend/users/p...')
#3 C:\xampp\apps\b4t\system\View\View.php(214): include('C:\\xampp\\apps\\b...')
#4 C:\xampp\apps\b4t\system\View\View.php(217): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#5 C:\xampp\apps\b4t\system\Common.php(1092): CodeIgniter\View\View->render('backend/users/s...', Array, true)
#6 C:\xampp\apps\b4t\app\Controllers\backend\UsersController.php(136): view('backend/users/s...', Array)
#7 C:\xampp\apps\b4t\system\CodeIgniter.php(802): App\Controllers\backend\UsersController->show(6)
#8 C:\xampp\apps\b4t\system\CodeIgniter.php(399): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\backend\UsersController))
#9 C:\xampp\apps\b4t\system\CodeIgniter.php(317): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\apps\b4t\index.php(37): CodeIgniter\CodeIgniter->run()
#11 {main}
CRITICAL - 2021-12-02 19:01:40 --> syntax error, unexpected 'if' (T_IF)
#0 C:\xampp\apps\b4t\system\View\View.php(217): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#1 C:\xampp\apps\b4t\system\Common.php(1092): CodeIgniter\View\View->render('backend/templat...', Array, true)
#2 C:\xampp\apps\b4t\app\Views\backend\template\main_view.php(1): view('backend/templat...')
#3 C:\xampp\apps\b4t\system\View\View.php(214): include('C:\\xampp\\apps\\b...')
#4 C:\xampp\apps\b4t\system\View\View.php(217): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#5 C:\xampp\apps\b4t\system\View\View.php(230): CodeIgniter\View\View->render('backend/templat...', Array, true)
#6 C:\xampp\apps\b4t\system\Common.php(1092): CodeIgniter\View\View->render('backend/users/s...', Array, true)
#7 C:\xampp\apps\b4t\app\Controllers\backend\UsersController.php(20): view('backend/users/s...', Array)
#8 C:\xampp\apps\b4t\system\CodeIgniter.php(802): App\Controllers\backend\UsersController->showAll()
#9 C:\xampp\apps\b4t\system\CodeIgniter.php(399): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\backend\UsersController))
#10 C:\xampp\apps\b4t\system\CodeIgniter.php(317): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\apps\b4t\index.php(37): CodeIgniter\CodeIgniter->run()
#12 {main}
CRITICAL - 2021-12-02 21:39:28 --> Object of class CodeIgniter\Session\Session could not be converted to string
#0 C:\xampp\apps\b4t\system\View\View.php(214): include()
#1 C:\xampp\apps\b4t\system\View\View.php(217): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#2 C:\xampp\apps\b4t\system\Common.php(1092): CodeIgniter\View\View->render('backend/templat...', Array, true)
#3 C:\xampp\apps\b4t\app\Views\backend\template\main_view.php(1): view('backend/templat...')
#4 C:\xampp\apps\b4t\system\View\View.php(214): include('C:\\xampp\\apps\\b...')
#5 C:\xampp\apps\b4t\system\View\View.php(217): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#6 C:\xampp\apps\b4t\system\View\View.php(230): CodeIgniter\View\View->render('backend/templat...', Array, true)
#7 C:\xampp\apps\b4t\system\Common.php(1092): CodeIgniter\View\View->render('backend/auth/se...', Array, true)
#8 C:\xampp\apps\b4t\app\Controllers\backend\AuthController.php(77): view('backend/auth/se...', Array)
#9 C:\xampp\apps\b4t\system\CodeIgniter.php(802): App\Controllers\backend\AuthController->setPassword()
#10 C:\xampp\apps\b4t\system\CodeIgniter.php(399): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\backend\AuthController))
#11 C:\xampp\apps\b4t\system\CodeIgniter.php(317): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\apps\b4t\index.php(37): CodeIgniter\CodeIgniter->run()
#13 {main}
CRITICAL - 2021-12-02 22:53:51 --> syntax error, unexpected '{'
#0 C:\xampp\apps\b4t\system\Autoloader\Autoloader.php(241): CodeIgniter\Autoloader\Autoloader->includeFile('C:\\xampp\\apps\\b...')
#1 C:\xampp\apps\b4t\system\Autoloader\Autoloader.php(219): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Libraries\\A...')
#2 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Libraries\\A...')
#3 C:\xampp\apps\b4t\app\Config\Services.php(102): spl_autoload_call('App\\Libraries\\A...')
#4 C:\xampp\apps\b4t\system\Config\BaseService.php(189): Config\Services::authorization(false)
#5 C:\xampp\apps\b4t\app\Config\Services.php(99): CodeIgniter\Config\BaseService::getSharedInstance('authorization')
#6 C:\xampp\apps\b4t\system\Common.php(932): Config\Services::authorization()
#7 C:\xampp\apps\b4t\app\Controllers\backend\BackendController.php(73): service('authorization')
#8 C:\xampp\apps\b4t\system\CodeIgniter.php(780): App\Controllers\backend\BackendController->initController(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), Object(CodeIgniter\Log\Logger))
#9 C:\xampp\apps\b4t\system\CodeIgniter.php(390): CodeIgniter\CodeIgniter->createController()
#10 C:\xampp\apps\b4t\system\CodeIgniter.php(317): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\apps\b4t\index.php(37): CodeIgniter\CodeIgniter->run()
#12 {main}
CRITICAL - 2021-12-02 22:55:19 --> Undefined property: App\Libraries\AuthorizationManager::$users_firstname
#0 C:\xampp\apps\b4t\app\Controllers\backend\BackendController.php(73): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined prope...', 'C:\\xampp\\apps\\b...', 73, Array)
#1 C:\xampp\apps\b4t\system\CodeIgniter.php(780): App\Controllers\backend\BackendController->initController(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), Object(CodeIgniter\Log\Logger))
#2 C:\xampp\apps\b4t\system\CodeIgniter.php(390): CodeIgniter\CodeIgniter->createController()
#3 C:\xampp\apps\b4t\system\CodeIgniter.php(317): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\apps\b4t\index.php(37): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2021-12-02 22:57:44 --> Trying to get property 'users_firstname' of non-object
#0 C:\xampp\apps\b4t\app\Controllers\backend\BackendController.php(73): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Trying to get p...', 'C:\\xampp\\apps\\b...', 73, Array)
#1 C:\xampp\apps\b4t\system\CodeIgniter.php(780): App\Controllers\backend\BackendController->initController(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), Object(CodeIgniter\Log\Logger))
#2 C:\xampp\apps\b4t\system\CodeIgniter.php(390): CodeIgniter\CodeIgniter->createController()
#3 C:\xampp\apps\b4t\system\CodeIgniter.php(317): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\apps\b4t\index.php(37): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2021-12-02 22:59:18 --> Trying to get property 'users_firstname' of non-object
#0 C:\xampp\apps\b4t\app\Controllers\backend\BackendController.php(73): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Trying to get p...', 'C:\\xampp\\apps\\b...', 73, Array)
#1 C:\xampp\apps\b4t\system\CodeIgniter.php(780): App\Controllers\backend\BackendController->initController(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), Object(CodeIgniter\Log\Logger))
#2 C:\xampp\apps\b4t\system\CodeIgniter.php(390): CodeIgniter\CodeIgniter->createController()
#3 C:\xampp\apps\b4t\system\CodeIgniter.php(317): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\apps\b4t\index.php(37): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2021-12-02 23:01:17 --> Call to undefined method App\Libraries\AuthorizationManager::ooo()
#0 C:\xampp\apps\b4t\system\CodeIgniter.php(780): App\Controllers\backend\BackendController->initController(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), Object(CodeIgniter\Log\Logger))
#1 C:\xampp\apps\b4t\system\CodeIgniter.php(390): CodeIgniter\CodeIgniter->createController()
#2 C:\xampp\apps\b4t\system\CodeIgniter.php(317): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 C:\xampp\htdocs\apps\b4t\index.php(37): CodeIgniter\CodeIgniter->run()
#4 {main}
CRITICAL - 2021-12-02 23:09:51 --> Call to a member function getRow() on bool
#0 C:\xampp\apps\b4t\system\CodeIgniter.php(780): App\Controllers\backend\BackendController->initController(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), Object(CodeIgniter\Log\Logger))
#1 C:\xampp\apps\b4t\system\CodeIgniter.php(390): CodeIgniter\CodeIgniter->createController()
#2 C:\xampp\apps\b4t\system\CodeIgniter.php(317): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 C:\xampp\htdocs\apps\b4t\index.php(37): CodeIgniter\CodeIgniter->run()
#4 {main}
CRITICAL - 2021-12-02 23:10:50 --> Call to a member function getRow() on bool
#0 C:\xampp\apps\b4t\system\CodeIgniter.php(780): App\Controllers\backend\BackendController->initController(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), Object(CodeIgniter\Log\Logger))
#1 C:\xampp\apps\b4t\system\CodeIgniter.php(390): CodeIgniter\CodeIgniter->createController()
#2 C:\xampp\apps\b4t\system\CodeIgniter.php(317): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 C:\xampp\htdocs\apps\b4t\index.php(37): CodeIgniter\CodeIgniter->run()
#4 {main}
CRITICAL - 2021-12-02 23:19:29 --> Undefined property: App\Controllers\backend\DashboardController::$authorization
#0 C:\xampp\apps\b4t\app\Controllers\backend\BackendController.php(74): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined prope...', 'C:\\xampp\\apps\\b...', 74, Array)
#1 C:\xampp\apps\b4t\system\CodeIgniter.php(780): App\Controllers\backend\BackendController->initController(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), Object(CodeIgniter\Log\Logger))
#2 C:\xampp\apps\b4t\system\CodeIgniter.php(390): CodeIgniter\CodeIgniter->createController()
#3 C:\xampp\apps\b4t\system\CodeIgniter.php(317): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\apps\b4t\index.php(37): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2021-12-02 23:23:29 --> Undefined property: App\Libraries\AuthorizationManager::$builder
#0 C:\xampp\apps\b4t\app\Libraries\AuthorizationManager.php(22): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined prope...', 'C:\\xampp\\apps\\b...', 22, Array)
#1 C:\xampp\apps\b4t\app\Controllers\backend\BackendController.php(74): App\Libraries\AuthorizationManager->isLoggedIn()
#2 C:\xampp\apps\b4t\system\CodeIgniter.php(780): App\Controllers\backend\BackendController->initController(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), Object(CodeIgniter\Log\Logger))
#3 C:\xampp\apps\b4t\system\CodeIgniter.php(390): CodeIgniter\CodeIgniter->createController()
#4 C:\xampp\apps\b4t\system\CodeIgniter.php(317): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 C:\xampp\htdocs\apps\b4t\index.php(37): CodeIgniter\CodeIgniter->run()
#6 {main}
CRITICAL - 2021-12-02 23:25:41 --> Undefined property: CodeIgniter\Database\MySQLi\Result::$users_firstname
#0 C:\xampp\apps\b4t\app\Controllers\backend\BackendController.php(76): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined prope...', 'C:\\xampp\\apps\\b...', 76, Array)
#1 C:\xampp\apps\b4t\system\CodeIgniter.php(780): App\Controllers\backend\BackendController->initController(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), Object(CodeIgniter\Log\Logger))
#2 C:\xampp\apps\b4t\system\CodeIgniter.php(390): CodeIgniter\CodeIgniter->createController()
#3 C:\xampp\apps\b4t\system\CodeIgniter.php(317): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\apps\b4t\index.php(37): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2021-12-02 23:27:31 --> syntax error, unexpected ';'
#0 C:\xampp\apps\b4t\system\Autoloader\Autoloader.php(241): CodeIgniter\Autoloader\Autoloader->includeFile('C:\\xampp\\apps\\b...')
#1 C:\xampp\apps\b4t\system\Autoloader\Autoloader.php(219): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Libraries\\A...')
#2 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Libraries\\A...')
#3 C:\xampp\apps\b4t\app\Config\Services.php(102): spl_autoload_call('App\\Libraries\\A...')
#4 C:\xampp\apps\b4t\system\Config\BaseService.php(189): Config\Services::authorization(false)
#5 C:\xampp\apps\b4t\app\Config\Services.php(99): CodeIgniter\Config\BaseService::getSharedInstance('authorization')
#6 C:\xampp\apps\b4t\system\Common.php(932): Config\Services::authorization()
#7 C:\xampp\apps\b4t\app\Controllers\backend\BackendController.php(73): service('authorization')
#8 C:\xampp\apps\b4t\system\CodeIgniter.php(780): App\Controllers\backend\BackendController->initController(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), Object(CodeIgniter\Log\Logger))
#9 C:\xampp\apps\b4t\system\CodeIgniter.php(390): CodeIgniter\CodeIgniter->createController()
#10 C:\xampp\apps\b4t\system\CodeIgniter.php(317): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\apps\b4t\index.php(37): CodeIgniter\CodeIgniter->run()
#12 {main}
CRITICAL - 2021-12-02 23:29:48 --> Trying to get property 'users_firstname' of non-object
#0 C:\xampp\apps\b4t\app\Controllers\backend\BackendController.php(76): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Trying to get p...', 'C:\\xampp\\apps\\b...', 76, Array)
#1 C:\xampp\apps\b4t\system\CodeIgniter.php(780): App\Controllers\backend\BackendController->initController(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), Object(CodeIgniter\Log\Logger))
#2 C:\xampp\apps\b4t\system\CodeIgniter.php(390): CodeIgniter\CodeIgniter->createController()
#3 C:\xampp\apps\b4t\system\CodeIgniter.php(317): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\apps\b4t\index.php(37): CodeIgniter\CodeIgniter->run()
#5 {main}
